import {readFile, writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';

// Reuse the versions already pinned by cloudflare/pnpm-lock.yaml. No network,
// floating package install, CDN, or additional browser dependency is involved.
const require = createRequire(import.meta.url);
const wranglerRequire = createRequire(require.resolve('../cloudflare/node_modules/wrangler/package.json'));
const miniflareRequire = createRequire(wranglerRequire.resolve('miniflare/package.json'));
const esbuild = wranglerRequire('esbuild');
const sharp = miniflareRequire('sharp');
const root = fileURLToPath(new URL('../', import.meta.url));
const original = new URL('../src/assets/chrome-knot.png', import.meta.url);

export async function buildAssets({check = false} = {}) {
  if(esbuild.version !== '0.28.1' || sharp.versions.sharp !== '0.35.4') {
    throw new Error('Asset tooling changed. Review output and update the pinned build versions explicitly.');
  }
  const result = await esbuild.build({
    absWorkingDir: root,
    entryPoints: ['src/scene.js'],
    bundle: true,
    format: 'esm',
    minify: true,
    write: false,
    legalComments: 'eof',
    target: ['es2020'],
    charset: 'utf8',
    banner: {js: '// Generated by scripts/build-assets.mjs. Edit src/scene.js, not this file.'}
  });
  const source = await readFile(original);
  const sculpture = await sharp(source).webp({lossless: true, effort: 6}).toBuffer();
  const [before, after] = await Promise.all([
    sharp(source).ensureAlpha().raw().toBuffer({resolveWithObject: true}),
    sharp(sculpture).ensureAlpha().raw().toBuffer({resolveWithObject: true})
  ]);
  if(before.info.width !== after.info.width || before.info.height !== after.info.height || before.info.channels !== 4 || after.info.channels !== 4) {
    throw new Error('The sculpture dimensions or alpha channel changed.');
  }
  // Encoders may canonicalize invisible RGB under fully transparent pixels.
  // Every alpha value and every visible colour channel must remain exact.
  for(let pixel = 0; pixel < before.data.length; pixel += 4) {
    if(before.data[pixel + 3] !== after.data[pixel + 3] || (before.data[pixel + 3] &&
      (before.data[pixel] !== after.data[pixel] || before.data[pixel + 1] !== after.data[pixel + 1] || before.data[pixel + 2] !== after.data[pixel + 2]))) {
      throw new Error('Lossless sculpture verification failed.');
    }
  }
  // Embedded vendor GLSL contains cosmetic trailing spaces; normalize those
  // as well as line endings so the generated file is clean in Git on Windows.
  const sceneCode = result.outputFiles[0].text.replace(/[\t ]+$/gm, '');
  const artifacts = [
    ['dist/scene.js', Buffer.from(sceneCode)],
    ['dist/assets/chrome-knot.webp', sculpture]
  ];
  for(const [name, bytes] of artifacts) {
    const destination = resolve(root, name);
    if(check) {
      const stored = await readFile(destination);
      const published = name.endsWith('.js') ? Buffer.from(stored.toString().replace(/\r\n/g, '\n')) : stored;
      if(!published.equals(bytes))throw new Error(`${name} is stale. Run node scripts/build-assets.mjs and commit the generated assets.`);
    } else await writeFile(destination, bytes);
    console.log(`${check ? 'Verified' : 'Built'} ${name}: ${bytes.length} bytes`);
  }
  console.log('Sculpture dimensions, visible RGB, and alpha verified lossless.');
}

if(process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await buildAssets({check: process.argv.includes('--check')});
}
